# Generated by Django 6.0.6 on 2026-06-25 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctorprofile_user'),
        ('schedule', '0003_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctor.doctorprofile'),
        ),
    ]
