# Generated by Django 6.0.6 on 2026-06-25 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_unique_together_and_more'),
        ('doctor', '0002_alter_doctorprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctorprofile'),
        ),
    ]
