# Generated by Django 6.0.6 on 2026-06-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorrequest',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
