# Generated by Django 6.0.6 on 2026-06-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctorrequest_fee_alter_doctorprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
